export const  USER_SIGNIN_REQUEST = 'USER_SIGN_IN_REQUEST'
export const  USER_SIGNIN_SUCCESS = 'USER_SIGN_IN_SUCCESS'
export const  USER_SIGNIN_FAIL = 'USER_SING_IN_FAIL'
export const  USER_SIGNOUT = 'USER_SIGNOUT'